### ISSUE TITLE
profile test should be dissolved from docker

### ISSUE THREAD

**Issue by tbugfinder** [nf-core/neutronstar#11]
https://github.com/nf-core/neutronstar/blob/157a0c904fd5c8de6a174a184aee4a0ac96a871b/conf/test.config#L9-L11

Shouldn't it be possible to run the test execution using singularity instead of docker?
Using `singularity,test` isn't possible right now.

**Comment by ewels** [comment]
Yes it should :+1:

In the short term, I think that `-profile test,singularity` _should_ work though. Profile order is important.. `-with-singularity` should also work.
